export const FETCH_SERVICES = 'FETCH_SERVICES';

export const ADD_INPUT_DATA = 'ADD_INPUT_DATA';
export const ADD_PHOTO = 'ADD_PHOTO';
export const REMOVE_PHOTO = 'REMOVE_PHOTO';
export const RESET_INPUTS_DATA = 'RESET_INPUTS_DATA';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMITTED_FORM_POPUP_WAS_SHOWN = 'SUBMITTED_FORM_POPUP_WAS_SHOWN';